-- This file is part of the LrMediaWiki2 project and distributed under the
-- terms of the MIT license (see LICENSE.txt file in the project root
-- directory).
--
-- HTML template for the browser-based SDC editor (see ToolEditSdcWeb.lua).
--
-- WHY THE PAGE IS BUILT FROM ORDINARY QUOTED STRINGS, one per line, instead
-- of one readable long-bracket string: the page contains "[[" and "]]"
-- (wikitext category links). A long-bracket string is the obvious way to
-- embed it, and it parses correctly in Lua 5.1 -- but the first build that
-- did so failed to load in Lightroom. Quoted strings have no bracket
-- semantics whatsoever, so this form cannot run into that class of problem
-- at all. It is harder to read; that is the price.
--
-- To change the page, edit sdc-editor.html and regenerate this file rather
-- than editing the strings below by hand.
--
-- The placeholder block between the PAYLOAD markers is replaced at runtime
-- with the values of the current photo. Opened directly in a browser, the
-- page still works and shows the sample data -- handy for trying out layout
-- changes without going through Lightroom.

local SdcEditorTemplate = {}

local L = {}

L[#L+1] = "<!DOCTYPE html>"
L[#L+1] = "<html lang=\"de\">"
L[#L+1] = "<head>"
L[#L+1] = "<meta charset=\"utf-8\">"
L[#L+1] = "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
L[#L+1] = "<title>LrMediaWiki – Strukturierte Daten</title>"
L[#L+1] = "<style>"
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Farben und Maße. Dunkel gehalten, weil dieser Editor aus Lightroom heraus"
L[#L+1] = "   aufgerufen wird – der Sprung in ein weißes Fenster blendet mitten in einer"
L[#L+1] = "   Durchsicht. QIDs, Sprachcodes und Wikitext laufen durchgehend in Monospace:"
L[#L+1] = "   das sind Bezeichner, keine Prosa."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = ":root{"
L[#L+1] = "  --bg:#191b1f; --panel:#22262b; --panel-2:#1e2126; --line:#33383f;"
L[#L+1] = "  --ink:#e7eaee; --muted:#8f98a3; --accent:#5fb3c4; --accent-dim:#2f5f69;"
L[#L+1] = "  --warn:#d4a24c; --danger:#c9705f;"
L[#L+1] = "  --ui:system-ui,-apple-system,\"Segoe UI\",Roboto,sans-serif;"
L[#L+1] = "  --mono:ui-monospace,SFMono-Regular,\"SF Mono\",Menlo,Consolas,monospace;"
L[#L+1] = "  --r:6px;"
L[#L+1] = "}"
L[#L+1] = "*{box-sizing:border-box}"
L[#L+1] = "html,body{margin:0;height:100%}"
L[#L+1] = "body{"
L[#L+1] = "  background:var(--bg); color:var(--ink); font:15px/1.5 var(--ui);"
L[#L+1] = "  -webkit-font-smoothing:antialiased;"
L[#L+1] = "}"
L[#L+1] = "button,input,textarea{font:inherit;color:inherit}"
L[#L+1] = ""
L[#L+1] = "/* Kopfzeile ---------------------------------------------------------------- */"
L[#L+1] = "header{"
L[#L+1] = "  position:sticky; top:0; z-index:20;"
L[#L+1] = "  display:flex; align-items:baseline; gap:1rem;"
L[#L+1] = "  padding:.85rem 1.25rem; background:var(--panel-2);"
L[#L+1] = "  border-bottom:1px solid var(--line);"
L[#L+1] = "}"
L[#L+1] = "header h1{margin:0; font-size:1rem; font-weight:600; letter-spacing:.01em}"
L[#L+1] = "header .file{font:13px var(--mono); color:var(--muted); flex:1;"
L[#L+1] = "  overflow:hidden; text-overflow:ellipsis; white-space:nowrap}"
L[#L+1] = "header .count{font:13px var(--mono); color:var(--muted)}"
L[#L+1] = "header select{background:var(--panel); color:var(--ink); border:1px solid var(--line);"
L[#L+1] = "  border-radius:var(--r); padding:.25rem .4rem; font:13px var(--ui)}"
L[#L+1] = ""
L[#L+1] = "/* Layout ------------------------------------------------------------------- */"
L[#L+1] = "main{"
L[#L+1] = "  display:grid; grid-template-columns:minmax(0,1fr) minmax(0,26rem);"
L[#L+1] = "  gap:1.5rem; padding:1.5rem 1.25rem 6rem; max-width:76rem; margin:0 auto;"
L[#L+1] = "}"
L[#L+1] = "@media (max-width:60rem){ main{grid-template-columns:minmax(0,1fr)} }"
L[#L+1] = ""
L[#L+1] = "section{"
L[#L+1] = "  background:var(--panel); border:1px solid var(--line);"
L[#L+1] = "  border-radius:var(--r); padding:1rem 1.1rem 1.15rem; margin-bottom:1.1rem;"
L[#L+1] = "}"
L[#L+1] = "section h2{"
L[#L+1] = "  margin:0 0 .1rem; font-size:.85rem; font-weight:600;"
L[#L+1] = "  letter-spacing:.06em; text-transform:uppercase; color:var(--ink);"
L[#L+1] = "}"
L[#L+1] = "section h2 .pid{font:12px var(--mono); color:var(--muted); margin-left:.5rem;"
L[#L+1] = "  letter-spacing:0; text-transform:none}"
L[#L+1] = "section .hint{margin:.15rem 0 .8rem; font-size:.82rem; color:var(--muted)}"
L[#L+1] = ""
L[#L+1] = "/* Eingaben ----------------------------------------------------------------- */"
L[#L+1] = "input[type=text], textarea{"
L[#L+1] = "  width:100%; background:var(--panel-2); border:1px solid var(--line);"
L[#L+1] = "  border-radius:var(--r); padding:.5rem .6rem; outline:none;"
L[#L+1] = "}"
L[#L+1] = "input[type=text]:focus, textarea:focus{"
L[#L+1] = "  border-color:var(--accent); box-shadow:0 0 0 2px var(--accent-dim);"
L[#L+1] = "}"
L[#L+1] = "textarea{font:13.5px/1.6 var(--mono); resize:vertical; min-height:7rem}"
L[#L+1] = "::placeholder{color:#6b737d}"
L[#L+1] = ""
L[#L+1] = "button{"
L[#L+1] = "  background:var(--panel-2); border:1px solid var(--line);"
L[#L+1] = "  border-radius:var(--r); padding:.45rem .8rem; cursor:pointer;"
L[#L+1] = "}"
L[#L+1] = "button:hover{border-color:var(--accent); color:#fff}"
L[#L+1] = "button:focus-visible{outline:2px solid var(--accent); outline-offset:2px}"
L[#L+1] = "button.primary{background:var(--accent); border-color:var(--accent); color:#10262b;"
L[#L+1] = "  font-weight:600}"
L[#L+1] = "button.primary:hover{filter:brightness(1.1); color:#10262b}"
L[#L+1] = ".rowline{display:flex; gap:.5rem; align-items:center}"
L[#L+1] = ".rowline > input{flex:1}"
L[#L+1] = ""
L[#L+1] = "/* Trefferliste ------------------------------------------------------------- */"
L[#L+1] = ".results{margin-top:.5rem; border:1px solid var(--line); border-radius:var(--r);"
L[#L+1] = "  overflow:hidden; display:none}"
L[#L+1] = ".results.open{display:block}"
L[#L+1] = ".results .hit{"
L[#L+1] = "  display:flex; gap:.6rem; align-items:baseline; width:100%;"
L[#L+1] = "  padding:.45rem .6rem; background:transparent; border:0; border-radius:0;"
L[#L+1] = "  text-align:left; cursor:pointer; border-bottom:1px solid var(--line);"
L[#L+1] = "}"
L[#L+1] = ".results .hit:last-child{border-bottom:0}"
L[#L+1] = ".results .hit:hover,.results .hit.sel{background:var(--accent-dim); color:#fff}"
L[#L+1] = ".results .hit .qid{font:12.5px var(--mono); color:var(--accent); flex:none}"
L[#L+1] = ".results .hit:hover .qid,.results .hit.sel .qid{color:#cfeff6}"
L[#L+1] = ".results .hit .lab{font-weight:500}"
L[#L+1] = ".results .hit .desc{color:var(--muted); font-size:.85em;"
L[#L+1] = "  overflow:hidden; text-overflow:ellipsis; white-space:nowrap}"
L[#L+1] = ".results .hit:hover .desc,.results .hit.sel .desc{color:#d7e6ea}"
L[#L+1] = ".results .state{padding:.45rem .6rem; color:var(--muted); font-size:.88rem}"
L[#L+1] = ""
L[#L+1] = "/* Chips: links der Bezeichner, rechts der Klartext – wie ein Inventaretikett */"
L[#L+1] = ".chips{display:flex; flex-wrap:wrap; gap:.4rem; margin-top:.6rem}"
L[#L+1] = ".chip{"
L[#L+1] = "  display:inline-flex; align-items:stretch; border:1px solid var(--line);"
L[#L+1] = "  border-radius:var(--r); background:var(--panel-2); overflow:hidden;"
L[#L+1] = "}"
L[#L+1] = ".chip .id{font:12.5px/1 var(--mono); color:var(--accent);"
L[#L+1] = "  padding:.4rem .5rem; display:flex; align-items:center;"
L[#L+1] = "  border-right:1px solid var(--line)}"
L[#L+1] = ".chip .lab{padding:.35rem .5rem; font-size:.9rem; display:flex; align-items:center}"
L[#L+1] = ".chip .lab.empty{color:var(--muted); font-style:italic}"
L[#L+1] = ".chip .x{"
L[#L+1] = "  border:0; background:transparent; border-left:1px solid var(--line);"
L[#L+1] = "  color:var(--muted); padding:0 .55rem; cursor:pointer; border-radius:0;"
L[#L+1] = "}"
L[#L+1] = ".chip .x:hover{background:var(--danger); color:#fff; border-color:var(--danger)}"
L[#L+1] = ".chips .none{color:var(--muted); font-size:.88rem; font-style:italic}"
L[#L+1] = ""
L[#L+1] = "/* Captions ----------------------------------------------------------------- */"
L[#L+1] = ".cap{display:flex; gap:.5rem; margin-bottom:.45rem; align-items:center}"
L[#L+1] = ".cap input.iso{width:5rem; font:13px var(--mono); text-align:center}"
L[#L+1] = ".cap input.txt{flex:1}"
L[#L+1] = ".cap .x{flex:none; padding:.45rem .6rem; color:var(--muted)}"
L[#L+1] = ".cap .x:hover{border-color:var(--danger); color:var(--danger)}"
L[#L+1] = ""
L[#L+1] = "/* Vorschau ----------------------------------------------------------------- */"
L[#L+1] = ".preview{position:sticky; top:4.2rem}"
L[#L+1] = ".preview pre{"
L[#L+1] = "  margin:0; padding:.85rem; background:var(--panel-2);"
L[#L+1] = "  border:1px solid var(--line); border-radius:var(--r);"
L[#L+1] = "  font:13px/1.65 var(--mono); white-space:pre-wrap; word-break:break-word;"
L[#L+1] = "  max-height:60vh; overflow:auto;"
L[#L+1] = "}"
L[#L+1] = ".preview .k{color:var(--accent)}"
L[#L+1] = ".preview .c{color:var(--muted)}"
L[#L+1] = ""
L[#L+1] = "/* Fußleiste ---------------------------------------------------------------- */"
L[#L+1] = "footer{"
L[#L+1] = "  position:fixed; left:0; right:0; bottom:0; z-index:20;"
L[#L+1] = "  display:flex; align-items:center; gap:.75rem;"
L[#L+1] = "  padding:.7rem 1.25rem; background:var(--panel-2);"
L[#L+1] = "  border-top:1px solid var(--line);"
L[#L+1] = "}"
L[#L+1] = "footer .status{flex:1; font-size:.88rem; color:var(--muted)}"
L[#L+1] = "footer .status.dirty{color:var(--warn)}"
L[#L+1] = "footer .status.done{color:var(--accent)}"
L[#L+1] = ""
L[#L+1] = ".done-panel{display:none; padding:1rem 1.25rem; background:var(--panel);"
L[#L+1] = "  border-top:1px solid var(--line)}"
L[#L+1] = ".done-panel.open{display:block}"
L[#L+1] = "</style>"
L[#L+1] = "</head>"
L[#L+1] = "<body>"
L[#L+1] = ""
L[#L+1] = "<header>"
L[#L+1] = "  <h1 data-i18n=\"appTitle\">Strukturierte Daten</h1>"
L[#L+1] = "  <span class=\"file\" id=\"fileName\">–</span>"
L[#L+1] = "  <span class=\"count\" id=\"photoCount\"></span>"
L[#L+1] = "  <select id=\"uiLang\" aria-label=\"Sprache / Language\"></select>"
L[#L+1] = "</header>"
L[#L+1] = ""
L[#L+1] = "<main>"
L[#L+1] = "  <div>"
L[#L+1] = "    <!-- Depicts ------------------------------------------------------------ -->"
L[#L+1] = "    <section>"
L[#L+1] = "      <h2><span data-i18n=\"depictsTitle\">Zeigt</span> <span class=\"pid\">P180</span></h2>"
L[#L+1] = "      <p class=\"hint\" data-i18n=\"depictsHint\"></p>"
L[#L+1] = "      <div class=\"rowline\">"
L[#L+1] = "        <input type=\"text\" id=\"depSearch\" data-i18n-ph=\"depictsSearchPh\""
L[#L+1] = "               autocomplete=\"off\" spellcheck=\"false\">"
L[#L+1] = "      </div>"
L[#L+1] = "      <div class=\"results\" id=\"depResults\"></div>"
L[#L+1] = "      <div class=\"chips\" id=\"depChips\"></div>"
L[#L+1] = "    </section>"
L[#L+1] = ""
L[#L+1] = "    <!-- Kategorien --------------------------------------------------------- -->"
L[#L+1] = "    <section>"
L[#L+1] = "      <h2 data-i18n=\"catTitle\">Kategorien</h2>"
L[#L+1] = "      <p class=\"hint\" data-i18n=\"catHint\"></p>"
L[#L+1] = "      <div class=\"rowline\">"
L[#L+1] = "        <input type=\"text\" id=\"catInput\" data-i18n-ph=\"catPh\""
L[#L+1] = "               autocomplete=\"off\">"
L[#L+1] = "        <button id=\"catSuggest\" data-i18n=\"catSuggest\">Aus Nummern vorschlagen</button>"
L[#L+1] = "      </div>"
L[#L+1] = "      <div class=\"chips\" id=\"catChips\"></div>"
L[#L+1] = "    </section>"
L[#L+1] = ""
L[#L+1] = "    <!-- Created during ----------------------------------------------------- -->"
L[#L+1] = "    <section>"
L[#L+1] = "      <h2><span data-i18n=\"cdTitle\">Entstanden bei</span> <span class=\"pid\">P10408</span></h2>"
L[#L+1] = "      <p class=\"hint\" data-i18n=\"cdHint\"></p>"
L[#L+1] = "      <div class=\"rowline\">"
L[#L+1] = "        <input type=\"text\" id=\"cdSearch\" data-i18n-ph=\"cdSearchPh\""
L[#L+1] = "               autocomplete=\"off\" spellcheck=\"false\">"
L[#L+1] = "      </div>"
L[#L+1] = "      <div class=\"results\" id=\"cdResults\"></div>"
L[#L+1] = "      <div class=\"chips\" id=\"cdChips\"></div>"
L[#L+1] = "    </section>"
L[#L+1] = ""
L[#L+1] = "    <!-- Bildunterschriften ------------------------------------------------- -->"
L[#L+1] = "    <section>"
L[#L+1] = "      <h2 data-i18n=\"capTitle\">Bildunterschriften</h2>"
L[#L+1] = "      <p class=\"hint\" data-i18n=\"capHint\"></p>"
L[#L+1] = "      <div id=\"caps\"></div>"
L[#L+1] = "      <div class=\"rowline\" style=\"margin-top:.6rem\">"
L[#L+1] = "        <button id=\"capAdd\" data-i18n=\"capAdd\">Sprache hinzufügen</button>"
L[#L+1] = "      </div>"
L[#L+1] = "    </section>"
L[#L+1] = ""
L[#L+1] = "    <!-- Wikitext ----------------------------------------------------------- -->"
L[#L+1] = "    <section>"
L[#L+1] = "      <h2 data-i18n=\"freeTitle\">Weiterer Wikitext</h2>"
L[#L+1] = "      <p class=\"hint\" data-i18n=\"freeHint\"></p>"
L[#L+1] = "      <textarea id=\"freetext\" spellcheck=\"false\"></textarea>"
L[#L+1] = "      <div class=\"rowline\" style=\"margin-top:.6rem\">"
L[#L+1] = "        <button id=\"sdcToWikitext\" data-i18n=\"sdcToWikitext\">SDC zu Wikitext</button>"
L[#L+1] = "      </div>"
L[#L+1] = "    </section>"
L[#L+1] = "  </div>"
L[#L+1] = ""
L[#L+1] = "  <!-- Vorschau ------------------------------------------------------------- -->"
L[#L+1] = "  <div>"
L[#L+1] = "    <div class=\"preview\">"
L[#L+1] = "      <section style=\"margin-bottom:0\">"
L[#L+1] = "        <h2 data-i18n=\"previewTitle\">Das wird gespeichert</h2>"
L[#L+1] = "        <p class=\"hint\" data-i18n=\"previewHint\"></p>"
L[#L+1] = "        <pre id=\"preview\"></pre>"
L[#L+1] = "      </section>"
L[#L+1] = "    </div>"
L[#L+1] = "  </div>"
L[#L+1] = "</main>"
L[#L+1] = ""
L[#L+1] = "<div class=\"done-panel\" id=\"donePanel\">"
L[#L+1] = "  <p id=\"doneText\"></p>"
L[#L+1] = "  <textarea id=\"doneData\" readonly style=\"min-height:5rem\"></textarea>"
L[#L+1] = "  <div class=\"rowline\" style=\"margin-top:.6rem\">"
L[#L+1] = "    <button id=\"copyBtn\" data-i18n=\"copy\">In die Zwischenablage</button>"
L[#L+1] = "  </div>"
L[#L+1] = "</div>"
L[#L+1] = ""
L[#L+1] = "<footer>"
L[#L+1] = "  <span class=\"status\" id=\"status\" data-i18n=\"ready\">Bereit.</span>"
L[#L+1] = "  <button id=\"revertBtn\" data-i18n=\"revert\">Änderungen verwerfen</button>"
L[#L+1] = "  <button class=\"primary\" id=\"saveBtn\" data-i18n=\"save\">Speichern und zu Lightroom</button>"
L[#L+1] = "</footer>"
L[#L+1] = ""
L[#L+1] = "<script>"
L[#L+1] = "\"use strict\";"
L[#L+1] = ""
L[#L+1] = "/* ==========================================================================="
L[#L+1] = "   Daten. Das Zusatzmodul ersetzt den Block zwischen den Markierungen durch"
L[#L+1] = "   die Werte des aktuellen Fotos; ohne Ersetzung stehen hier Beispieldaten,"
L[#L+1] = "   damit sich die Datei auch allein öffnen und prüfen lässt."
L[#L+1] = "   =========================================================================== */"
L[#L+1] = "/*__PAYLOAD_START__*/"
L[#L+1] = "var PAYLOAD = {"
L[#L+1] = "  fileName: \"KRI_2026_1834.dng\","
L[#L+1] = "  photoCount: 1,"
L[#L+1] = "  returnPort: 0,            /* 0 = kein Rückweg, nur Anzeigen und Kopieren */"
L[#L+1] = "  token: \"\","
L[#L+1] = "  uiLang: \"\",            /* leer = Sprache des Browsers */"
L[#L+1] = "  depicts: \"Q640 # Harald Krichel; Q42 # Douglas Adams\","
L[#L+1] = "  createdDuring: \"Q124692383 # Berlinale 2026\","
L[#L+1] = "  categories: \"Berlinale 2026; Harald Krichel\","
L[#L+1] = "  captions: { de: \"Harald Krichel bei der Berlinale 2026\", en: \"\" },"
L[#L+1] = "  freetext: \"{{Information}}\\n[[Category:Photographs by Harald Krichel]]\""
L[#L+1] = "};"
L[#L+1] = "/*__PAYLOAD_END__*/"
L[#L+1] = ""
L[#L+1] = ""
L[#L+1] = "/* ==========================================================================="
L[#L+1] = "   Sprachen. STRINGS ist die einzige Stelle, an der Oberflächentexte stehen –"
L[#L+1] = "   eine weitere Sprache ist eine weitere Tabelle, sonst nichts. Fehlt ein"
L[#L+1] = "   Schlüssel in einer Sprache, greift Englisch, dann der Schlüsselname selbst;"
L[#L+1] = "   eine unvollständige Übersetzung bricht also nichts."
L[#L+1] = "   Platzhalter im Text: {0}, {1} …"
L[#L+1] = "   =========================================================================== */"
L[#L+1] = "var STRINGS = {"
L[#L+1] = "  de: {"
L[#L+1] = "    langName: \"Deutsch\","
L[#L+1] = "    appTitle: \"Strukturierte Daten\","
L[#L+1] = "    depictsTitle: \"Zeigt\","
L[#L+1] = "    depictsHint: \"Was auf dem Bild zu sehen ist. Ab drei Buchstaben wird gesucht; Treffer mit Klick oder Eingabetaste übernehmen. Eine bekannte Nummer kann direkt eingetippt werden.\","
L[#L+1] = "    depictsSearchPh: \"Namen suchen oder Q1234567\","
L[#L+1] = "    depictsEmpty: \"Noch nichts zugeordnet.\","
L[#L+1] = "    catTitle: \"Kategorien\","
L[#L+1] = "    catHint: \"Ohne das Präfix „Category:“. Eingabetaste fügt hinzu.\","
L[#L+1] = "    catPh: \"Berlinale 2026\","
L[#L+1] = "    catSuggest: \"Aus Nummern vorschlagen\","
L[#L+1] = "    catEmpty: \"Keine Kategorien.\","
L[#L+1] = "    cdTitle: \"Entstanden bei\","
L[#L+1] = "    cdHint: \"Die Veranstaltung, etwa ein Filmfestival. Nur ein Eintrag.\","
L[#L+1] = "    cdSearchPh: \"Veranstaltung suchen oder Q1234567\","
L[#L+1] = "    cdEmpty: \"Keine Veranstaltung.\","
L[#L+1] = "    capTitle: \"Bildunterschriften\","
L[#L+1] = "    capHint: \"Je Sprache eine Zeile. Sprachcode links ist frei überschreibbar.\","
L[#L+1] = "    capAdd: \"Sprache hinzufügen\","
L[#L+1] = "    capLangLabel: \"Sprachcode\","
L[#L+1] = "    capTextPh: \"Bildunterschrift auf {0}\","
L[#L+1] = "    capRemove: \"Zeile entfernen\","
L[#L+1] = "    freeTitle: \"Weiterer Wikitext\","
L[#L+1] = "    freeHint: \"Alles, was nicht als strukturierte Daten abgelegt wird – Vorlagen, Kommentare, Beschreibungsblöcke.\","
L[#L+1] = "    sdcToWikitext: \"SDC zu Wikitext\","
L[#L+1] = "    previewTitle: \"Das wird gespeichert\","
L[#L+1] = "    previewHint: \"Der Inhalt des Felds „Wikitext“, genau so, wie das Zusatzmodul ihn ablegt.\","
L[#L+1] = "    previewEmpty: \"(leer)\","
L[#L+1] = "    save: \"Speichern und zu Lightroom\","
L[#L+1] = "    revert: \"Änderungen verwerfen\","
L[#L+1] = "    copy: \"In die Zwischenablage\","
L[#L+1] = "    remove: \"Entfernen\","
L[#L+1] = "    noLabel: \"ohne Bezeichnung\","
L[#L+1] = "    ready: \"Bereit.\","
L[#L+1] = "    unsaved: \"Nicht gespeichert.\","
L[#L+1] = "    searching: \"Suche …\","
L[#L+1] = "    noHits: \"Nichts gefunden.\","
L[#L+1] = "    offline: \"Wikidata ist gerade nicht erreichbar.\","
L[#L+1] = "    enterApplies: \"Eingabetaste übernimmt {0}\","
L[#L+1] = "    noQids: \"Keine Nummern eingetragen, aus denen sich Kategorien ableiten ließen.\","
L[#L+1] = "    catsAdded: \"{0} Kategorie(n) ergänzt – bitte prüfen.\","
L[#L+1] = "    nothingNew: \"Nichts Neues gefunden.\","
L[#L+1] = "    allInWikitext: \"Es steht schon alles im Wikitext.\","
L[#L+1] = "    linesAppended: \"{0} Zeile(n) an den Wikitext angehängt.\","
L[#L+1] = "    reverted: \"Auf den Stand aus Lightroom zurückgesetzt.\","
L[#L+1] = "    copied: \"Kopiert.\","
L[#L+1] = "    copyFailed: \"Kopieren hat nicht geklappt – bitte von Hand.\","
L[#L+1] = "    downloaded: \"Datei heruntergeladen – Lightroom übernimmt sie automatisch.\","
L[#L+1] = "    downloadedLong: \"Die Datei wurde heruntergeladen. Lightroom holt sie sich automatisch aus dem Downloads-Ordner – das dauert höchstens ein paar Sekunden.\\n\\nFalls der Browser nach dem Speicherort gefragt hat: bitte den Downloads-Ordner verwenden, damit Lightroom die Datei findet.\","
L[#L+1] = "    photosSelected: \"{0} Fotos ausgewählt\""
L[#L+1] = "  },"
L[#L+1] = "  en: {"
L[#L+1] = "    langName: \"English\","
L[#L+1] = "    appTitle: \"Structured data\","
L[#L+1] = "    depictsTitle: \"Depicts\","
L[#L+1] = "    depictsHint: \"What can be seen in the picture. Searching starts at three characters; apply a hit by clicking it or pressing Enter. A known item number can be typed in directly.\","
L[#L+1] = "    depictsSearchPh: \"Search a name or Q1234567\","
L[#L+1] = "    depictsEmpty: \"Nothing assigned yet.\","
L[#L+1] = "    catTitle: \"Categories\","
L[#L+1] = "    catHint: \"Without the “Category:” prefix. Enter adds one.\","
L[#L+1] = "    catPh: \"Berlinale 2026\","
L[#L+1] = "    catSuggest: \"Suggest from item numbers\","
L[#L+1] = "    catEmpty: \"No categories.\","
L[#L+1] = "    cdTitle: \"Created during\","
L[#L+1] = "    cdHint: \"The event, a film festival for instance. One entry only.\","
L[#L+1] = "    cdSearchPh: \"Search an event or Q1234567\","
L[#L+1] = "    cdEmpty: \"No event.\","
L[#L+1] = "    capTitle: \"Captions\","
L[#L+1] = "    capHint: \"One line per language. The language code on the left can be overwritten freely.\","
L[#L+1] = "    capAdd: \"Add a language\","
L[#L+1] = "    capLangLabel: \"Language code\","
L[#L+1] = "    capTextPh: \"Caption in {0}\","
L[#L+1] = "    capRemove: \"Remove this line\","
L[#L+1] = "    freeTitle: \"Further wikitext\","
L[#L+1] = "    freeHint: \"Everything that is not stored as structured data – templates, comments, description blocks.\","
L[#L+1] = "    sdcToWikitext: \"SDC to wikitext\","
L[#L+1] = "    previewTitle: \"What will be saved\","
L[#L+1] = "    previewHint: \"The contents of the “Wikitext” field, exactly as the plug-in stores them.\","
L[#L+1] = "    previewEmpty: \"(empty)\","
L[#L+1] = "    save: \"Save and back to Lightroom\","
L[#L+1] = "    revert: \"Discard changes\","
L[#L+1] = "    copy: \"Copy to clipboard\","
L[#L+1] = "    remove: \"Remove\","
L[#L+1] = "    noLabel: \"no label\","
L[#L+1] = "    ready: \"Ready.\","
L[#L+1] = "    unsaved: \"Not saved.\","
L[#L+1] = "    searching: \"Searching …\","
L[#L+1] = "    noHits: \"Nothing found.\","
L[#L+1] = "    offline: \"Wikidata cannot be reached right now.\","
L[#L+1] = "    enterApplies: \"Enter applies {0}\","
L[#L+1] = "    noQids: \"No item numbers entered that categories could be derived from.\","
L[#L+1] = "    catsAdded: \"{0} category/categories added – please check.\","
L[#L+1] = "    nothingNew: \"Nothing new found.\","
L[#L+1] = "    allInWikitext: \"Everything is in the wikitext already.\","
L[#L+1] = "    linesAppended: \"{0} line(s) appended to the wikitext.\","
L[#L+1] = "    reverted: \"Reset to the state from Lightroom.\","
L[#L+1] = "    copied: \"Copied.\","
L[#L+1] = "    copyFailed: \"Copying did not work – please do it by hand.\","
L[#L+1] = "    downloaded: \"File downloaded – Lightroom picks it up automatically.\","
L[#L+1] = "    downloadedLong: \"The file has been downloaded. Lightroom fetches it from the Downloads folder automatically – this takes a few seconds at most.\\n\\nIf the browser asked where to save it: please use the Downloads folder so that Lightroom finds it.\","
L[#L+1] = "    photosSelected: \"{0} photos selected\""
L[#L+1] = "  }"
L[#L+1] = "};"
L[#L+1] = ""
L[#L+1] = "var UI = \"en\";"
L[#L+1] = ""
L[#L+1] = "function t(key) {"
L[#L+1] = "  var table = STRINGS[UI] || {};"
L[#L+1] = "  var s = table[key];"
L[#L+1] = "  if (s === undefined) s = (STRINGS.en || {})[key];"
L[#L+1] = "  if (s === undefined) return key;"
L[#L+1] = "  for (var i = 1; i < arguments.length; i++) {"
L[#L+1] = "    s = s.split(\"{\" + (i - 1) + \"}\").join(String(arguments[i]));"
L[#L+1] = "  }"
L[#L+1] = "  return s;"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Setzt alle mit data-i18n bzw. data-i18n-ph markierten Texte neu. */"
L[#L+1] = "function applyStrings() {"
L[#L+1] = "  var nodes = document.querySelectorAll(\"[data-i18n]\");"
L[#L+1] = "  for (var i = 0; i < nodes.length; i++) {"
L[#L+1] = "    nodes[i].textContent = t(nodes[i].getAttribute(\"data-i18n\"));"
L[#L+1] = "  }"
L[#L+1] = "  nodes = document.querySelectorAll(\"[data-i18n-ph]\");"
L[#L+1] = "  for (var j = 0; j < nodes.length; j++) {"
L[#L+1] = "    nodes[j].placeholder = t(nodes[j].getAttribute(\"data-i18n-ph\"));"
L[#L+1] = "  }"
L[#L+1] = "  document.documentElement.lang = UI;"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function pickUiLang() {"
L[#L+1] = "  var wanted = PAYLOAD.uiLang || (navigator.language || \"en\").slice(0, 2);"
L[#L+1] = "  return STRINGS[wanted] ? wanted : \"en\";"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "var API = \"https://www.wikidata.org/w/api.php\";"
L[#L+1] = "var MIN_CHARS = 3, DEBOUNCE = 250, MAX_HITS = 8;"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Zustand. depicts und createdDuring sind Listen aus {id, label}; die"
L[#L+1] = "   Zeichenketten des Zusatzmoduls werden beim Laden zerlegt und beim Speichern"
L[#L+1] = "   wieder zusammengesetzt."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "var state = { depicts: [], createdDuring: null, categories: [], captions: [],"
L[#L+1] = "              freetext: \"\" };"
L[#L+1] = "var dirty = false;"
L[#L+1] = ""
L[#L+1] = "function splitTokens(s){"
L[#L+1] = "  return String(s || \"\").split(/[;,]/).map(function(t){ return t.trim(); })"
L[#L+1] = "         .filter(function(t){ return t !== \"\"; });"
L[#L+1] = "}"
L[#L+1] = "function parseToken(tok){"
L[#L+1] = "  var hash = tok.indexOf(\"#\");"
L[#L+1] = "  var id = (hash < 0 ? tok : tok.slice(0, hash)).trim();"
L[#L+1] = "  var label = hash < 0 ? \"\" : tok.slice(hash + 1).trim();"
L[#L+1] = "  var m = id.match(/^[Qq](\\d+)$/);"
L[#L+1] = "  return m ? { id: \"Q\" + m[1], label: label } : null;"
L[#L+1] = "}"
L[#L+1] = "function tokenText(e){ return e.label ? e.id + \" # \" + e.label : e.id; }"
L[#L+1] = ""
L[#L+1] = "function load(){"
L[#L+1] = "  state.depicts = splitTokens(PAYLOAD.depicts).map(parseToken)"
L[#L+1] = "                  .filter(Boolean);"
L[#L+1] = "  var cd = splitTokens(PAYLOAD.createdDuring).map(parseToken).filter(Boolean);"
L[#L+1] = "  state.createdDuring = cd.length ? cd[0] : null;"
L[#L+1] = "  state.categories = splitTokens(PAYLOAD.categories);"
L[#L+1] = "  state.captions = [];"
L[#L+1] = "  var caps = PAYLOAD.captions || {};"
L[#L+1] = "  [\"de\",\"en\",\"fr\",\"it\"].forEach(function(l){"
L[#L+1] = "    state.captions.push({ lang: l, text: caps[l] || \"\" });"
L[#L+1] = "  });"
L[#L+1] = "  Object.keys(caps).forEach(function(l){"
L[#L+1] = "    if ([\"de\",\"en\",\"fr\",\"it\"].indexOf(l) < 0) {"
L[#L+1] = "      state.captions.push({ lang: l, text: caps[l] });"
L[#L+1] = "    }"
L[#L+1] = "  });"
L[#L+1] = "  state.freetext = PAYLOAD.freetext || \"\";"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Wikidata. Erst die Präfixsuche, und wenn die zu wenig hergibt, zusätzlich"
L[#L+1] = "   die Volltextsuche – dieselbe Staffelung wie im Zusatzmodul, damit"
L[#L+1] = "   umgestellte Wortfolgen und Ordnungszahlen gefunden werden."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function api(params){"
L[#L+1] = "  params.format = \"json\";"
L[#L+1] = "  params.origin = \"*\";"
L[#L+1] = "  var q = Object.keys(params).map(function(k){"
L[#L+1] = "    return encodeURIComponent(k) + \"=\" + encodeURIComponent(params[k]);"
L[#L+1] = "  }).join(\"&\");"
L[#L+1] = "  return fetch(API + \"?\" + q).then(function(r){ return r.json(); });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Sprachen, in denen gesucht wird. Für Personen ist das meist gleichgültig –"
L[#L+1] = "   ein Name lautet überall gleich. Für Sachen nicht: „Kamera“, „camera“ und"
L[#L+1] = "   „appareil photo“ sind drei verschiedene Zeichenketten, und die Präfixsuche"
L[#L+1] = "   von Wikidata findet nur, was in der abgefragten Sprache steht. Deshalb wird"
L[#L+1] = "   in mehreren Sprachen zugleich gesucht: in der Oberflächensprache, auf"
L[#L+1] = "   Englisch als der am besten gepflegten Sprache, und in allen Sprachen, für"
L[#L+1] = "   die dieses Foto bereits eine Bildunterschrift hat – wer italienische"
L[#L+1] = "   Captions schreibt, sucht vermutlich auch mit italienischen Begriffen. */"
L[#L+1] = "function searchLanguages() {"
L[#L+1] = "  var out = [], seen = {};"
L[#L+1] = "  function add(l) {"
L[#L+1] = "    l = (l || \"\").trim().toLowerCase();"
L[#L+1] = "    if (/^[a-z]{2}[a-z0-9-]*$/.test(l) && !seen[l] && out.length < 4) {"
L[#L+1] = "      seen[l] = true; out.push(l);"
L[#L+1] = "    }"
L[#L+1] = "  }"
L[#L+1] = "  add(UI);"
L[#L+1] = "  add(\"en\");"
L[#L+1] = "  state.captions.forEach(function(c){ add(c.lang); });"
L[#L+1] = "  return out;"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function searchPrefix(term, lang){"
L[#L+1] = "  return api({ action:\"wbsearchentities\", search:term, language:lang,"
L[#L+1] = "               uselang:UI, type:\"item\", limit:5 })"
L[#L+1] = "    .then(function(d){"
L[#L+1] = "      return (d.search || []).map(function(e){"
L[#L+1] = "        return { id:e.id, label:e.label || \"\", description:e.description || \"\" };"
L[#L+1] = "      });"
L[#L+1] = "    })"
L[#L+1] = "    .catch(function(){ return []; });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Volltextsuche. Sie durchsucht Wikidata sprachübergreifend und ist damit die"
L[#L+1] = "   breiteste Stufe – auch für Sprachen, die oben nicht abgefragt werden. */"
L[#L+1] = "function searchFulltext(term){"
L[#L+1] = "  return api({ action:\"query\", list:\"search\", srsearch:term,"
L[#L+1] = "               srnamespace:0, srlimit:MAX_HITS })"
L[#L+1] = "    .then(function(d){"
L[#L+1] = "      var ids = ((d.query && d.query.search) || [])"
L[#L+1] = "        .map(function(e){ return e.title; })"
L[#L+1] = "        .filter(function(t){ return /^Q\\d+$/.test(t); });"
L[#L+1] = "      if (!ids.length) return [];"
L[#L+1] = "      return fetchLabels(ids);"
L[#L+1] = "    })"
L[#L+1] = "    .catch(function(){ return []; });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Bezeichnungen und Beschreibungen zu einer QID-Liste, in der Reihenfolge der"
L[#L+1] = "   Liste. Bevorzugt die Oberflächensprache, dann Englisch, dann irgendeine"
L[#L+1] = "   vorhandene – so bleibt eine Zeile auch dann lesbar, wenn es die Bezeichnung"
L[#L+1] = "   in den ersten beiden Sprachen nicht gibt. */"
L[#L+1] = "function fetchLabels(ids){"
L[#L+1] = "  return api({ action:\"wbgetentities\", ids:ids.join(\"|\"),"
L[#L+1] = "               props:\"labels|descriptions\" })"
L[#L+1] = "    .then(function(d2){"
L[#L+1] = "      var ents = d2.entities || {};"
L[#L+1] = "      return ids.map(function(id){"
L[#L+1] = "        var e = ents[id];"
L[#L+1] = "        if (!e || e.missing !== undefined) return null;"
L[#L+1] = "        function pick(tbl){"
L[#L+1] = "          if (!tbl) return \"\";"
L[#L+1] = "          var v = tbl[UI] || tbl.en;"
L[#L+1] = "          if (!v) {"
L[#L+1] = "            for (var k in tbl) { if (tbl[k] && tbl[k].value) { v = tbl[k]; break; } }"
L[#L+1] = "          }"
L[#L+1] = "          return v ? v.value : \"\";"
L[#L+1] = "        }"
L[#L+1] = "        return { id:id, label:pick(e.labels), description:pick(e.descriptions) };"
L[#L+1] = "      }).filter(Boolean);"
L[#L+1] = "    })"
L[#L+1] = "    .catch(function(){ return []; });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Alle Stufen PARALLEL: die Präfixsuchen je Sprache und die Volltextsuche"
L[#L+1] = "   laufen gleichzeitig, nicht nacheinander – dadurch kostet die breitere Suche"
L[#L+1] = "   kaum mehr Zeit als die alte einsprachige. Zusammengeführt wird in der"
L[#L+1] = "   Reihenfolge der Sprachen (Oberflächensprache zuerst), die Volltexttreffer"
L[#L+1] = "   hängen hinten an. */"
L[#L+1] = "function search(term){"
L[#L+1] = "  var langs = searchLanguages();"
L[#L+1] = "  var jobs = langs.map(function(l){ return searchPrefix(term, l); });"
L[#L+1] = "  jobs.push(searchFulltext(term));"
L[#L+1] = "  return Promise.all(jobs).then(function(lists){"
L[#L+1] = "    var seen = {}, out = [];"
L[#L+1] = "    lists.forEach(function(list){"
L[#L+1] = "      list.forEach(function(r){"
L[#L+1] = "        if (r.id && !seen[r.id] && out.length < MAX_HITS) {"
L[#L+1] = "          seen[r.id] = true; out.push(r);"
L[#L+1] = "        }"
L[#L+1] = "      });"
L[#L+1] = "    });"
L[#L+1] = "    return out;"
L[#L+1] = "  });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Suchfeld mit Trefferliste. Pfeiltasten wählen, Eingabetaste übernimmt,"
L[#L+1] = "   Escape schließt – das ist der Teil, den ein Lightroom-Dialog nicht kann."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function wireSearch(inputId, listId, onPick){"
L[#L+1] = "  var input = document.getElementById(inputId);"
L[#L+1] = "  var list = document.getElementById(listId);"
L[#L+1] = "  var timer = null, generation = 0, hits = [], sel = -1;"
L[#L+1] = ""
L[#L+1] = "  function close(){ list.classList.remove(\"open\"); list.innerHTML = \"\";"
L[#L+1] = "                    hits = []; sel = -1; }"
L[#L+1] = "  function render(){"
L[#L+1] = "    list.innerHTML = \"\";"
L[#L+1] = "    hits.forEach(function(h, i){"
L[#L+1] = "      var b = document.createElement(\"button\");"
L[#L+1] = "      b.className = \"hit\" + (i === sel ? \" sel\" : \"\");"
L[#L+1] = "      b.type = \"button\";"
L[#L+1] = "      b.innerHTML = '<span class=\"qid\"></span><span class=\"lab\"></span>' +"
L[#L+1] = "                    '<span class=\"desc\"></span>';"
L[#L+1] = "      b.querySelector(\".qid\").textContent = h.id;"
L[#L+1] = "      b.querySelector(\".lab\").textContent = h.label || h.id;"
L[#L+1] = "      b.querySelector(\".desc\").textContent = h.description || \"\";"
L[#L+1] = "      b.addEventListener(\"click\", function(){ take(h); });"
L[#L+1] = "      list.appendChild(b);"
L[#L+1] = "    });"
L[#L+1] = "    list.classList.add(\"open\");"
L[#L+1] = "  }"
L[#L+1] = "  function state_(text){"
L[#L+1] = "    list.innerHTML = '<div class=\"state\"></div>';"
L[#L+1] = "    list.firstChild.textContent = text;"
L[#L+1] = "    list.classList.add(\"open\");"
L[#L+1] = "  }"
L[#L+1] = "  function take(hit){"
L[#L+1] = "    onPick({ id: hit.id, label: hit.label || \"\" });"
L[#L+1] = "    input.value = \"\"; close(); input.focus();"
L[#L+1] = "  }"
L[#L+1] = ""
L[#L+1] = "  input.addEventListener(\"input\", function(){"
L[#L+1] = "    var term = input.value.trim();"
L[#L+1] = "    generation++;"
L[#L+1] = "    var mine = generation;"
L[#L+1] = "    if (timer) clearTimeout(timer);"
L[#L+1] = "    var direct = parseToken(term);"
L[#L+1] = "    if (direct && /^[Qq]\\d+$/.test(term.replace(/#.*$/, \"\").trim())) {"
L[#L+1] = "      state_(t(\"enterApplies\", direct.id));"
L[#L+1] = "      hits = [{ id: direct.id, label: direct.label, description: \"\" }];"
L[#L+1] = "      sel = 0;"
L[#L+1] = "      return;"
L[#L+1] = "    }"
L[#L+1] = "    if (term.length < MIN_CHARS) { close(); return; }"
L[#L+1] = "    state_(t(\"searching\"));"
L[#L+1] = "    timer = setTimeout(function(){"
L[#L+1] = "      search(term).then(function(res){"
L[#L+1] = "        if (mine !== generation) return;"
L[#L+1] = "        hits = res; sel = res.length ? 0 : -1;"
L[#L+1] = "        if (!res.length) { state_(t(\"noHits\")); return; }"
L[#L+1] = "        render();"
L[#L+1] = "      }).catch(function(){"
L[#L+1] = "        if (mine !== generation) return;"
L[#L+1] = "        state_(t(\"offline\"));"
L[#L+1] = "      });"
L[#L+1] = "    }, DEBOUNCE);"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  input.addEventListener(\"keydown\", function(ev){"
L[#L+1] = "    if (ev.key === \"ArrowDown\" || ev.key === \"ArrowUp\") {"
L[#L+1] = "      if (!hits.length) return;"
L[#L+1] = "      ev.preventDefault();"
L[#L+1] = "      sel += (ev.key === \"ArrowDown\" ? 1 : -1);"
L[#L+1] = "      if (sel < 0) sel = hits.length - 1;"
L[#L+1] = "      if (sel >= hits.length) sel = 0;"
L[#L+1] = "      render();"
L[#L+1] = "    } else if (ev.key === \"Enter\") {"
L[#L+1] = "      if (sel >= 0 && hits[sel]) { ev.preventDefault(); take(hits[sel]); }"
L[#L+1] = "    } else if (ev.key === \"Escape\") {"
L[#L+1] = "      close();"
L[#L+1] = "    }"
L[#L+1] = "  });"
L[#L+1] = "  input.addEventListener(\"blur\", function(){ setTimeout(close, 180); });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Darstellung"
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function chip(id, label, onRemove){"
L[#L+1] = "  var el = document.createElement(\"span\");"
L[#L+1] = "  el.className = \"chip\";"
L[#L+1] = "  var i = document.createElement(\"span\"); i.className = \"id\"; i.textContent = id;"
L[#L+1] = "  var l = document.createElement(\"span\");"
L[#L+1] = "  l.className = \"lab\" + (label ? \"\" : \" empty\");"
L[#L+1] = "  l.textContent = label || t(\"noLabel\");"
L[#L+1] = "  var x = document.createElement(\"button\");"
L[#L+1] = "  x.className = \"x\"; x.type = \"button\"; x.title = t(\"remove\");"
L[#L+1] = "  x.textContent = \"✕\";"
L[#L+1] = "  x.addEventListener(\"click\", onRemove);"
L[#L+1] = "  el.appendChild(i); el.appendChild(l); el.appendChild(x);"
L[#L+1] = "  return el;"
L[#L+1] = "}"
L[#L+1] = "function plainChip(text, onRemove){"
L[#L+1] = "  var el = document.createElement(\"span\");"
L[#L+1] = "  el.className = \"chip\";"
L[#L+1] = "  var l = document.createElement(\"span\"); l.className = \"lab\"; l.textContent = text;"
L[#L+1] = "  var x = document.createElement(\"button\");"
L[#L+1] = "  x.className = \"x\"; x.type = \"button\"; x.title = t(\"remove\");"
L[#L+1] = "  x.textContent = \"✕\";"
L[#L+1] = "  x.addEventListener(\"click\", onRemove);"
L[#L+1] = "  el.appendChild(l); el.appendChild(x);"
L[#L+1] = "  return el;"
L[#L+1] = "}"
L[#L+1] = "function emptyNote(box, text){"
L[#L+1] = "  var n = document.createElement(\"span\");"
L[#L+1] = "  n.className = \"none\"; n.textContent = text;"
L[#L+1] = "  box.appendChild(n);"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function renderDepicts(){"
L[#L+1] = "  var box = document.getElementById(\"depChips\");"
L[#L+1] = "  box.innerHTML = \"\";"
L[#L+1] = "  if (!state.depicts.length) { emptyNote(box, t(\"depictsEmpty\")); return; }"
L[#L+1] = "  state.depicts.forEach(function(e, i){"
L[#L+1] = "    box.appendChild(chip(e.id, e.label, function(){"
L[#L+1] = "      state.depicts.splice(i, 1); touch(); renderDepicts();"
L[#L+1] = "    }));"
L[#L+1] = "  });"
L[#L+1] = "}"
L[#L+1] = "function renderCreatedDuring(){"
L[#L+1] = "  var box = document.getElementById(\"cdChips\");"
L[#L+1] = "  box.innerHTML = \"\";"
L[#L+1] = "  if (!state.createdDuring) { emptyNote(box, t(\"cdEmpty\")); return; }"
L[#L+1] = "  var e = state.createdDuring;"
L[#L+1] = "  box.appendChild(chip(e.id, e.label, function(){"
L[#L+1] = "    state.createdDuring = null; touch(); renderCreatedDuring();"
L[#L+1] = "  }));"
L[#L+1] = "}"
L[#L+1] = "function renderCategories(){"
L[#L+1] = "  var box = document.getElementById(\"catChips\");"
L[#L+1] = "  box.innerHTML = \"\";"
L[#L+1] = "  if (!state.categories.length) { emptyNote(box, t(\"catEmpty\")); return; }"
L[#L+1] = "  state.categories.forEach(function(c, i){"
L[#L+1] = "    box.appendChild(plainChip(c, function(){"
L[#L+1] = "      state.categories.splice(i, 1); touch(); renderCategories();"
L[#L+1] = "    }));"
L[#L+1] = "  });"
L[#L+1] = "}"
L[#L+1] = "function renderCaptions(){"
L[#L+1] = "  var box = document.getElementById(\"caps\");"
L[#L+1] = "  box.innerHTML = \"\";"
L[#L+1] = "  state.captions.forEach(function(c, i){"
L[#L+1] = "    var row = document.createElement(\"div\"); row.className = \"cap\";"
L[#L+1] = "    var iso = document.createElement(\"input\");"
L[#L+1] = "    iso.type = \"text\"; iso.className = \"iso\"; iso.value = c.lang;"
L[#L+1] = "    iso.setAttribute(\"aria-label\", t(\"capLangLabel\"));"
L[#L+1] = "    iso.addEventListener(\"input\", function(){"
L[#L+1] = "      c.lang = iso.value.trim().toLowerCase(); touch();"
L[#L+1] = "    });"
L[#L+1] = "    var txt = document.createElement(\"input\");"
L[#L+1] = "    txt.type = \"text\"; txt.className = \"txt\"; txt.value = c.text;"
L[#L+1] = "    txt.placeholder = t(\"capTextPh\", c.lang || \"…\");"
L[#L+1] = "    txt.addEventListener(\"input\", function(){ c.text = txt.value; touch(); });"
L[#L+1] = "    var x = document.createElement(\"button\");"
L[#L+1] = "    x.className = \"x\"; x.type = \"button\"; x.textContent = \"✕\";"
L[#L+1] = "    x.title = t(\"capRemove\");"
L[#L+1] = "    x.addEventListener(\"click\", function(){"
L[#L+1] = "      state.captions.splice(i, 1); touch(); renderCaptions();"
L[#L+1] = "    });"
L[#L+1] = "    row.appendChild(iso); row.appendChild(txt); row.appendChild(x);"
L[#L+1] = "    box.appendChild(row);"
L[#L+1] = "  });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* Der Wikitext, genau im Format des Zusatzmoduls: je Nummer eine eigene"
L[#L+1] = "   depicts-Zeile, danach created_during, dann der freie Text. */"
L[#L+1] = "function buildWikitext(){"
L[#L+1] = "  var parts = [], seen = {};"
L[#L+1] = "  state.captions.forEach(function(c){"
L[#L+1] = "    var l = (c.lang || \"\").trim().toLowerCase();"
L[#L+1] = "    var t = (c.text || \"\").trim();"
L[#L+1] = "    if (/^[a-z]{2}[a-z0-9-]*$/.test(l) && t && !seen[l]) {"
L[#L+1] = "      seen[l] = true;"
L[#L+1] = "      parts.push(\"caption_\" + l + \"=\" + t);"
L[#L+1] = "    }"
L[#L+1] = "  });"
L[#L+1] = "  state.depicts.forEach(function(e){ parts.push(\"depicts=\" + tokenText(e)); });"
L[#L+1] = "  if (state.createdDuring) {"
L[#L+1] = "    parts.push(\"created_during=\" + tokenText(state.createdDuring));"
L[#L+1] = "  }"
L[#L+1] = "  var ft = (state.freetext || \"\").trim();"
L[#L+1] = "  if (ft) parts.push(ft);"
L[#L+1] = "  return parts.join(\"\\n\");"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function renderPreview(){"
L[#L+1] = "  var pre = document.getElementById(\"preview\");"
L[#L+1] = "  var text = buildWikitext();"
L[#L+1] = "  pre.innerHTML = \"\";"
L[#L+1] = "  if (!text) { pre.textContent = t(\"previewEmpty\"); return; }"
L[#L+1] = "  text.split(\"\\n\").forEach(function(line){"
L[#L+1] = "    var m = line.match(/^([a-z_0-9]+)=(.*)$/);"
L[#L+1] = "    if (m) {"
L[#L+1] = "      var k = document.createElement(\"span\");"
L[#L+1] = "      k.className = \"k\"; k.textContent = m[1] + \"=\";"
L[#L+1] = "      pre.appendChild(k);"
L[#L+1] = "      var rest = m[2], h = rest.indexOf(\"#\");"
L[#L+1] = "      if (h >= 0) {"
L[#L+1] = "        pre.appendChild(document.createTextNode(rest.slice(0, h)));"
L[#L+1] = "        var c = document.createElement(\"span\");"
L[#L+1] = "        c.className = \"c\"; c.textContent = rest.slice(h);"
L[#L+1] = "        pre.appendChild(c);"
L[#L+1] = "      } else {"
L[#L+1] = "        pre.appendChild(document.createTextNode(rest));"
L[#L+1] = "      }"
L[#L+1] = "    } else {"
L[#L+1] = "      pre.appendChild(document.createTextNode(line));"
L[#L+1] = "    }"
L[#L+1] = "    pre.appendChild(document.createTextNode(\"\\n\"));"
L[#L+1] = "  });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function renderAll(){"
L[#L+1] = "  renderDepicts(); renderCreatedDuring(); renderCategories();"
L[#L+1] = "  renderCaptions(); renderPreview();"
L[#L+1] = "  document.getElementById(\"freetext\").value = state.freetext;"
L[#L+1] = "}"
L[#L+1] = "function touch(){"
L[#L+1] = "  dirty = true;"
L[#L+1] = "  var s = document.getElementById(\"status\");"
L[#L+1] = "  s.className = \"status dirty\";"
L[#L+1] = "  s.textContent = t(\"unsaved\");"
L[#L+1] = "  renderPreview();"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Kategorievorschläge: zu jeder eingetragenen Nummer die Commons-Kategorie"
L[#L+1] = "   (P373) holen, ersatzweise die englische Bezeichnung."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function suggestCategories(){"
L[#L+1] = "  var ids = state.depicts.map(function(e){ return e.id; });"
L[#L+1] = "  if (state.createdDuring) ids.push(state.createdDuring.id);"
L[#L+1] = "  var btn = document.getElementById(\"catSuggest\");"
L[#L+1] = "  if (!ids.length) { setStatus(t(\"noQids\")); return; }"
L[#L+1] = "  btn.disabled = true;"
L[#L+1] = "  var old = btn.textContent;"
L[#L+1] = "  btn.textContent = t(\"searching\");"
L[#L+1] = "  api({ action:\"wbgetentities\", ids:ids.slice(0,50).join(\"|\"),"
L[#L+1] = "        props:\"claims|labels\", languages:\"en\" })  /* Kategorienamen sind englisch */"
L[#L+1] = "  .then(function(d){"
L[#L+1] = "    var ents = d.entities || {}, added = 0;"
L[#L+1] = "    var have = {};"
L[#L+1] = "    state.categories.forEach(function(c){ have[c.toLowerCase()] = true; });"
L[#L+1] = "    ids.forEach(function(id){"
L[#L+1] = "      var e = ents[id];"
L[#L+1] = "      if (!e || e.missing !== undefined) return;"
L[#L+1] = "      var name = \"\";"
L[#L+1] = "      var claims = (e.claims || {}).P373 || [];"
L[#L+1] = "      for (var i = 0; i < claims.length; i++) {"
L[#L+1] = "        var c = claims[i];"
L[#L+1] = "        if (c.rank !== \"deprecated\" && c.mainsnak &&"
L[#L+1] = "            c.mainsnak.snaktype === \"value\" &&"
L[#L+1] = "            typeof c.mainsnak.datavalue.value === \"string\") {"
L[#L+1] = "          name = c.mainsnak.datavalue.value.trim(); break;"
L[#L+1] = "        }"
L[#L+1] = "      }"
L[#L+1] = "      if (!name && e.labels && e.labels.en) name = e.labels.en.value.trim();"
L[#L+1] = "      if (name && !have[name.toLowerCase()]) {"
L[#L+1] = "        have[name.toLowerCase()] = true;"
L[#L+1] = "        state.categories.push(name);"
L[#L+1] = "        added++;"
L[#L+1] = "      }"
L[#L+1] = "    });"
L[#L+1] = "    renderCategories();"
L[#L+1] = "    if (added) { touch(); setStatus(t(\"catsAdded\", added)); }"
L[#L+1] = "    else setStatus(t(\"nothingNew\"));"
L[#L+1] = "  })"
L[#L+1] = "  .catch(function(){ setStatus(t(\"offline\")); })"
L[#L+1] = "  .then(function(){ btn.disabled = false; btn.textContent = old; });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function setStatus(text, kind){"
L[#L+1] = "  var s = document.getElementById(\"status\");"
L[#L+1] = "  s.className = \"status\" + (kind ? \" \" + kind : (dirty ? \" dirty\" : \"\"));"
L[#L+1] = "  s.textContent = text;"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Speichern. Der Rückweg zu Lightroom läuft über den Loopback-Port: die Daten"
L[#L+1] = "   werden in Stücke zerlegt, damit sie sicher in eine Adresszeile passen, und"
L[#L+1] = "   der Reihe nach abgeschickt. Ohne Port (Datei allein geöffnet) wird das"
L[#L+1] = "   Ergebnis nur angezeigt."
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function payloadOut(){"
L[#L+1] = "  var caps = {};"
L[#L+1] = "  state.captions.forEach(function(c){"
L[#L+1] = "    var l = (c.lang || \"\").trim().toLowerCase();"
L[#L+1] = "    var t = (c.text || \"\").trim();"
L[#L+1] = "    if (/^[a-z]{2}[a-z0-9-]*$/.test(l) && t) caps[l] = t;"
L[#L+1] = "  });"
L[#L+1] = "  return {"
L[#L+1] = "    token: PAYLOAD.token || \"\","
L[#L+1] = "    uiLang: UI,"
L[#L+1] = "    depicts: state.depicts.map(tokenText).join(\"; \"),"
L[#L+1] = "    createdDuring: state.createdDuring ? tokenText(state.createdDuring) : \"\","
L[#L+1] = "    categories: state.categories.join(\"; \"),"
L[#L+1] = "    captions: caps,"
L[#L+1] = "    freetext: state.freetext || \"\","
L[#L+1] = "    wikitext: buildWikitext()"
L[#L+1] = "  };"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* -----------------------------------------------------------------------"
L[#L+1] = "   Rückweg: kein Netzwerk, keine Ports, kein Warten. Die Seite löst einen"
L[#L+1] = "   DATEIDOWNLOAD aus – eine JSON-Datei mit festem Namen, die im Downloads-"
L[#L+1] = "   Ordner landet. In Lightroom läuft ein stiller Beobachter, der alle zwei"
L[#L+1] = "   Sekunden nachsieht, ob die Datei aufgetaucht ist. Kein LrSocket, kein"
L[#L+1] = "   fetch, keine Portbelegung, keine Schutzsoftware im Weg."
L[#L+1] = ""
L[#L+1] = "   Voraussetzung: der Browser ist so eingestellt, dass Downloads ohne"
L[#L+1] = "   Rückfrage im Standardordner landen. Falls nicht, kommt ein Dateidialog"
L[#L+1] = "   dazwischen – funktioniert trotzdem, nur ein Klick mehr."
L[#L+1] = "   ----------------------------------------------------------------------- */"
L[#L+1] = ""
L[#L+1] = "var RESULT_FILENAME = \"lrmediawiki-sdc-result.json\";"
L[#L+1] = ""
L[#L+1] = "function triggerDownload(text, filename) {"
L[#L+1] = "  var blob = new Blob([text], { type: \"application/json\" });"
L[#L+1] = "  var url = URL.createObjectURL(blob);"
L[#L+1] = "  var a = document.createElement(\"a\");"
L[#L+1] = "  a.href = url;"
L[#L+1] = "  a.download = filename;"
L[#L+1] = "  document.body.appendChild(a);"
L[#L+1] = "  a.click();"
L[#L+1] = "  setTimeout(function() {"
L[#L+1] = "    document.body.removeChild(a);"
L[#L+1] = "    URL.revokeObjectURL(url);"
L[#L+1] = "  }, 200);"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function save(){"
L[#L+1] = "  var out = JSON.stringify(payloadOut(), null, 2);"
L[#L+1] = "  triggerDownload(out, RESULT_FILENAME);"
L[#L+1] = "  dirty = false;"
L[#L+1] = "  setStatus(t(\"downloaded\"), \"done\");"
L[#L+1] = "  showDone(t(\"downloadedLong\"), buildWikitext());"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function showDone(text, data){"
L[#L+1] = "  document.getElementById(\"doneText\").textContent = text;"
L[#L+1] = "  document.getElementById(\"doneData\").value = data;"
L[#L+1] = "  document.getElementById(\"donePanel\").classList.add(\"open\");"
L[#L+1] = "  document.getElementById(\"doneData\").scrollIntoView({ behavior:\"smooth\","
L[#L+1] = "                                                       block:\"center\" });"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "/* ---------------------------------------------------------------------------"
L[#L+1] = "   Verdrahtung"
L[#L+1] = "--------------------------------------------------------------------------- */"
L[#L+1] = "function setUiLang(lang){"
L[#L+1] = "  UI = STRINGS[lang] ? lang : \"en\";"
L[#L+1] = "  applyStrings();"
L[#L+1] = "  renderAll();"
L[#L+1] = "  setStatus(t(\"ready\"));"
L[#L+1] = "}"
L[#L+1] = ""
L[#L+1] = "function init(){"
L[#L+1] = "  load();"
L[#L+1] = "  UI = pickUiLang();"
L[#L+1] = ""
L[#L+1] = "  /* Sprachauswahl aus der Tabelle aufbauen – eine weitere Sprache in STRINGS"
L[#L+1] = "     erscheint hier automatisch, ohne weitere Änderung. */"
L[#L+1] = "  var sel = document.getElementById(\"uiLang\");"
L[#L+1] = "  Object.keys(STRINGS).forEach(function(code){"
L[#L+1] = "    var o = document.createElement(\"option\");"
L[#L+1] = "    o.value = code;"
L[#L+1] = "    o.textContent = STRINGS[code].langName || code;"
L[#L+1] = "    sel.appendChild(o);"
L[#L+1] = "  });"
L[#L+1] = "  sel.value = UI;"
L[#L+1] = "  sel.addEventListener(\"change\", function(){ setUiLang(sel.value); });"
L[#L+1] = "  applyStrings();"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"fileName\").textContent = PAYLOAD.fileName || \"\";"
L[#L+1] = "  var n = Number(PAYLOAD.photoCount || 1);"
L[#L+1] = "  document.getElementById(\"photoCount\").textContent ="
L[#L+1] = "    n > 1 ? t(\"photosSelected\", n) : \"\";"
L[#L+1] = ""
L[#L+1] = "  renderAll();"
L[#L+1] = ""
L[#L+1] = "  wireSearch(\"depSearch\", \"depResults\", function(e){"
L[#L+1] = "    if (!state.depicts.some(function(x){ return x.id === e.id; })) {"
L[#L+1] = "      state.depicts.push(e);"
L[#L+1] = "    }"
L[#L+1] = "    touch(); renderDepicts();"
L[#L+1] = "  });"
L[#L+1] = "  wireSearch(\"cdSearch\", \"cdResults\", function(e){"
L[#L+1] = "    state.createdDuring = e; touch(); renderCreatedDuring();"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  var catInput = document.getElementById(\"catInput\");"
L[#L+1] = "  catInput.addEventListener(\"keydown\", function(ev){"
L[#L+1] = "    if (ev.key !== \"Enter\") return;"
L[#L+1] = "    ev.preventDefault();"
L[#L+1] = "    var v = catInput.value.trim().replace(/^Category:\\s*/i, \"\");"
L[#L+1] = "    if (!v) return;"
L[#L+1] = "    if (!state.categories.some(function(c){"
L[#L+1] = "          return c.toLowerCase() === v.toLowerCase(); })) {"
L[#L+1] = "      state.categories.push(v);"
L[#L+1] = "    }"
L[#L+1] = "    catInput.value = \"\"; touch(); renderCategories();"
L[#L+1] = "  });"
L[#L+1] = "  document.getElementById(\"catSuggest\").addEventListener(\"click\", suggestCategories);"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"capAdd\").addEventListener(\"click\", function(){"
L[#L+1] = "    state.captions.push({ lang: \"\", text: \"\" });"
L[#L+1] = "    renderCaptions();"
L[#L+1] = "    var rows = document.querySelectorAll(\"#caps .cap input.iso\");"
L[#L+1] = "    if (rows.length) rows[rows.length - 1].focus();"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"freetext\").addEventListener(\"input\", function(ev){"
L[#L+1] = "    state.freetext = ev.target.value; touch();"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"sdcToWikitext\").addEventListener(\"click\", function(){"
L[#L+1] = "    /* Hängt beides in einem Schritt an: Bildunterschriften als"
L[#L+1] = "       {{sprache|1=…}}-Blöcke und Kategorien als [[Category:…]]-Zeilen."
L[#L+1] = "       Mehrfaches Klicken schadet nicht – was schon dasteht, kommt nicht"
L[#L+1] = "       noch einmal dazu. */"
L[#L+1] = "    var add = [];"
L[#L+1] = "    state.captions.forEach(function(c){"
L[#L+1] = "      var l = (c.lang || \"\").trim().toLowerCase(), t = (c.text || \"\").trim();"
L[#L+1] = "      if (!/^[a-z]{2}[a-z0-9-]*$/.test(l) || !t) return;"
L[#L+1] = "      var block = \"{{\" + l + \"|1=\" + t + \"}}\";"
L[#L+1] = "      if (state.freetext.indexOf(block) < 0 && add.indexOf(block) < 0) add.push(block);"
L[#L+1] = "    });"
L[#L+1] = "    state.categories.forEach(function(c){"
L[#L+1] = "      var line = \"[[Category:\" + c + \"]]\";"
L[#L+1] = "      if (state.freetext.indexOf(line) < 0 && add.indexOf(line) < 0) add.push(line);"
L[#L+1] = "    });"
L[#L+1] = "    if (!add.length) { setStatus(t(\"allInWikitext\")); return; }"
L[#L+1] = "    state.freetext = (state.freetext ? state.freetext + \"\\n\" : \"\") + add.join(\"\\n\");"
L[#L+1] = "    document.getElementById(\"freetext\").value = state.freetext;"
L[#L+1] = "    touch();"
L[#L+1] = "    setStatus(t(\"linesAppended\", add.length));"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"revertBtn\").addEventListener(\"click\", function(){"
L[#L+1] = "    load(); dirty = false; renderAll();"
L[#L+1] = "    document.getElementById(\"donePanel\").classList.remove(\"open\");"
L[#L+1] = "    setStatus(t(\"reverted\"));"
L[#L+1] = "  });"
L[#L+1] = "  document.getElementById(\"saveBtn\").addEventListener(\"click\", save);"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"copyBtn\").addEventListener(\"click\", function(){"
L[#L+1] = "    var ta = document.getElementById(\"doneData\");"
L[#L+1] = "    ta.select();"
L[#L+1] = "    try { document.execCommand(\"copy\"); setStatus(t(\"copied\")); }"
L[#L+1] = "    catch (e) { setStatus(t(\"copyFailed\")); }"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  document.addEventListener(\"keydown\", function(ev){"
L[#L+1] = "    if ((ev.metaKey || ev.ctrlKey) && ev.key === \"s\") { ev.preventDefault(); save(); }"
L[#L+1] = "  });"
L[#L+1] = "  window.addEventListener(\"beforeunload\", function(ev){"
L[#L+1] = "    if (dirty) { ev.preventDefault(); ev.returnValue = \"\"; }"
L[#L+1] = "  });"
L[#L+1] = ""
L[#L+1] = "  document.getElementById(\"depSearch\").focus();"
L[#L+1] = "}"
L[#L+1] = "init();"
L[#L+1] = "</script>"
L[#L+1] = "</body>"
L[#L+1] = "</html>"
L[#L+1] = ""

SdcEditorTemplate.html = table.concat(L, "\n")

return SdcEditorTemplate
